---
title: Een slimme meid herkent gekkigheid
author: Peter Hoffenaar
date: '2019-02-18'
slug: een-slimme-meid-herkent-gekkigheid
categories:
  - Kinderen
  - Onderzoek
  - M/V verschillen
tags:
  - Wiskunde
  - Self fulfilling prophecy
archives: '2019'
---
_'Schoolmeiden laten zich niet zomaar van de wijs brengen’_, twitterde wetenschapsjournalist [Ronald Veldhuizen](www.ronaldveldhuizen.com) naar aanleiding van de meest omvangrijke studie tot nu toe naar de vraag of meisjes slechter gaan presteren als ze te horen krijgen dat ze slechter zijn in wiskunde (een _self fulfilling prophecy_ die bekend staat als het _stereotype threat effect_). 

In plaats van de gebruikelijke 100 tot 250, bestond de steekproef uit 2064 dertien- en Nederlandse scholieren. Omdat Paulette Flore van Tilburg University ook nog eens de hypothesen en haar analyseplan van tevoren vastlegde in een zogenoemde pre-registratie kunnen we met recht spreken van [methodologisch meedogenloos](https://www.tijdschriftdepsycholoog.nl/wetenschap/matige-milde-en-meedogenloze-methoden/) onderzoek. 

Een blik op de resultaten leert ons dat meisjes die te horen kregen dat ze slechter zouden zijn in wiskunde dan jongens op geen enkele manier afweken van meisjes die te horen kregen dat jongens en meisjes ongeveer gelijk scoren. Geen verschil in het cijfer op de toets en ook geen verschil op de makkelijke of moeilijke vragen. 

Er was al twijfel of je een stereotyperende uitspraak een zaadje in iemands hoofd plant dat leidt tot onderpresteren, maar nu is deze theorie nog onwaarschijnlijker geworden. De tijd lijkt rijp om op zoek te gaan naar andere verklaringen voor de verschillen in wiskundeprestaties tussen jongens en meisjes!

Flore, P. C., Mulder, J., & Wicherts, J. M. (2018). The influence of gender stereotype threat on mathematics test scores of Dutch high school students: a registered report. Comprehensive Results in Social Psychology, 3(2), 140–174. https://doi.org/10.1080/23743603.2018.1559647